server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB


  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          facebook:
            client-id: 908264090410986
            client-secret: 024c81a22d42bd36d623f06b7b5e887e
            scope:
              - public-profile
              - email
# S3
cloud:
  aws:
    s3:
      bucket: ${bucket}
    credentials:
      access-key: ${accessKey}
      secret-key: ${secretKey}
    region:
      static: ${region}
      auto: false
    stack:
      auto: false


base-url: ${s3-base-url}

jwt:
  header: Authorization
  secret: ${jwtSecretKey}
